### ISSUE TITLE
Missing Connection: White Sands -> Secret History

### ISSUE THREAD

**Issue by dauthleikr** [PaleoCrafter/reading-order#19]
I believe Khriss meets Kelsier in Secret History :)
Edit: I just saw that you put the Khriss marker on secret history, but no connection. So this is intended?

**Comment by jofwu** [comment]
You mean Khriss meeting Wax? If you hover over the Khriss marker it should give the details of the reference.

The intent is to pick up Hoid, Khriss, and Nazh with the special markers because they are kind of a special case. Khriss is the odd one out in that she _does_ have a "primary" book to point at, but at the same time she's almost better known for the Ars Arcanum. So I guess it's kind of a toss up on how to treat her. :)

**Comment by dauthleikr** [comment]
No, I meant Kelsier meeting Khriss and Nazh in the cognitive realm. I guess you can keep it as it is, it's fine. 

I just listened to mostly graphic audio audiobooks, and since you for example do not see any maps that way, khriss and nazh don't appear to be everywhere like hoid. When I read (heard) secret history, I was a bit confused about her appearance since I couldn't really connect her to other books, and only reading white sand as the final cosmere piece cleared that up. That's why I felt there was an arrow missing, but admittedly, it's more of an audiobook related problem.
